package com.apssouza.mytrade.trading.forex.session.event;

public enum EventType {

    SIGNAL_CREATED, ORDER_CREATED, ORDER_FILLED, POSITION_OPENED, POSITION_CLOSED, NEW_LOOP,ORDER_FOUND, STOP_ORDER_FILLED, PORTFOLIO_CHANGED, PRICE_UPDATED;
}
